### ISSUE TITLE
请问有客户端嘛

### ISSUE THREAD

**Issue by akirarika** [Kaier33/Tiny-Monitor-Js-Server-Side#1]
已 Star！非常期待！ (๑´ㅂ`๑)

有考虑客户端部分的 SDK 怎么写嘛，如果还没写的话，我或许可以帮忙去写

Nodejs 的服务端我不是很擅长，不过我有一些好的想法

我的邮箱是 i@喵.chat 可以向我发邮件 然后我们加个企鹅好友！

**Comment by Kaier33** [comment]
sdk有的哈. 只是目前来看, 写得比较搓哈哈哈哈
https://github.com/Kaier33/Tiny-Monitor-Js-SDK

**Comment by Kaier33** [comment]
大概讲下计划 ~~小饼~~:
  
服务端 咕咕咕(bushi) todo :
1. 现在只是做了上报接口, 用Redis做消息队列 应对一下并发问题...
2. 用户登录 /注册, jwt, 项目创建/管理 等还没做
3. 提供接口给 可视化平台做数据展示用
4. 邮件告警通知
5. docker部署还没整
6. 等等

关于客户端 sdk嘛.
我看其他前端探针项目 大概得都收集了 3大块内容:  错误异常, 性能指标, 用户行为.
我只是觉得这样做要收集上报的东西就就太多了, 只想做错误异常收集 ~~毕竟我比较懒~~
毕竟 性能问题 我可以开 F12看, 用户操作行为也这种交给各种 第三方统计(百度, 友盟这种) ~~真是懒到了极致呢~~

目前自己的写的sdk还有很多问题没有解决. 
1. 比如还没对 react 和小程序进行支持. 
2. errorId 的生成规则 和 格式 过于简单
3. 上报策略 不友好 
4. 感觉还是得记录一下用户操作的行为, 捕获错误时同时上报最近 10 ~20 的操作记录 🤔
5. 代码太丑 ~~捂头大哭~~

当然, 你可以自己写个sdk. 我去给你star. 哈哈 
@akirarika
